<?php

namespace Fab\Messenger\Controller;

use Fab\Messenger\Domain\Repository\SentMessageRepository;
use Psr\Http\Message\ResponseInterface;
use TYPO3\CMS\Backend\Template\ModuleTemplateFactory;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;

// the module template will be initialized in handleRequest()

class AdminModuleController extends ActionController
{
    protected $tableName = 'tx_messenger_domain_model_sentmessage';
    protected SentMessageRepository $sentMessageRepository;
    protected ModuleTemplateFactory $moduleTemplateFactory;

    public function __construct()
    {
        $this->sentMessageRepository = GeneralUtility::makeInstance(SentMessageRepository::class);
        $this->moduleTemplateFactory = GeneralUtility::makeInstance(ModuleTemplateFactory::class);
    }

    public function initializeAction()
    {
        parent::initializeAction(); // TODO: Change the autogenerated stub
    }

    public function indexAction(): ResponseInterface
    {
        $messages = $this->sentMessageRepository->findAll();
        $this->view->assign('messages', $messages);
        $moduleTemplate = $this->moduleTemplateFactory->create($this->request);
        $moduleTemplate->setContent($this->view->render());
        return $this->htmlResponse($moduleTemplate->renderContent());
    }
}
